
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

interface ServerResponseProps {
  data: {
    name: string;
    email: string;
    message: string;
    timestamp: string;
  } | null;
}

const ServerResponse: React.FC<ServerResponseProps> = ({ data }) => {
  // Format the timestamp for display if it exists
  const formattedTime = data?.timestamp 
    ? new Date(data.timestamp).toLocaleString() 
    : null;

  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle>Server-Side Rendered Response</CardTitle>
        <CardDescription>
          This simulates what would be generated by a server using EJS or similar
        </CardDescription>
      </CardHeader>
      <CardContent>
        {!data ? (
          <div className="min-h-[300px] flex items-center justify-center border-2 border-dashed border-gray-200 rounded-md p-4">
            <p className="text-gray-400 text-center">
              Submit the form to see the server response here...
            </p>
          </div>
        ) : (
          <div className="border border-gray-200 rounded-md p-4 bg-gray-50">
            <div className="mb-4 pb-2 border-b border-gray-200">
              <div className="text-sm text-gray-500">Server processed this data at:</div>
              <div className="font-mono text-xs">{formattedTime}</div>
            </div>
            
            <div className="space-y-3">
              <div>
                <h3 className="text-sm font-medium text-gray-500">Name:</h3>
                <p className="font-medium">{data.name}</p>
              </div>
              
              <div>
                <h3 className="text-sm font-medium text-gray-500">Email:</h3>
                <p className="font-medium">{data.email}</p>
              </div>
              
              <div>
                <h3 className="text-sm font-medium text-gray-500">Message:</h3>
                <p className="whitespace-pre-wrap">{data.message}</p>
              </div>
            </div>
            
            <div className="mt-6 pt-4 border-t border-gray-200">
              <div className="text-xs text-gray-500">
                <code className="bg-gray-100 p-1 rounded">
                  {`<!-- This HTML was "rendered" on the server -->`}
                </code>
              </div>
              <pre className="mt-2 text-xs bg-gray-100 p-2 rounded overflow-x-auto">
                {`<!DOCTYPE html>
<html>
<head>
  <title>Server Response</title>
</head>
<body>
  <h1>Hello, ${data.name}!</h1>
  <p>We've received your message: "${data.message}"</p>
  <p>We'll contact you at: ${data.email}</p>
  <p>Timestamp: ${formattedTime}</p>
</body>
</html>`}
              </pre>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default ServerResponse;
